### ISSUE TITLE
Update the README.md for Hacktoberfest.

### ISSUE THREAD

**Issue by utkarsh1311** [mitul3737/HacktoberfestDemo#4]
## I want to improve the README.md file by 

- ### Adding some banners about Hacktoberfest like this one :
![Hacktoberfest_final_2color-06 copy](https://user-images.githubusercontent.com/70108561/134692649-89736b79-7ca4-402a-98b4-4bbce4072f3a.png)

**Comment by mitul3737** [comment]
I have assigned you
